### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by shader** [cjdrake/boolexpr#20]
```
$ pip install boolexpr

Collecting boolexpr
  Using cached boolexpr-2.3.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-ud7he4ld/boolexpr/setup.py", line 25, in <module>
        with open(join("/home/cjdrake/Downloads/src/github.com/cjdrake/boolexpr", "README.rst")) as fin:
    FileNotFoundError: [Errno 2] No such file or directory: '/home/cjdrake/Downloads/src/github.com/cjdrake/boolexpr/README.rst'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ud7he4ld/boolexpr/
```

**Comment by cjdrake** [comment]
Darn cmake :)

How come it's trying to install the zip file, not the wheel?

Here's the Python3.5 "manylinux" [wheel](https://pypi.python.org/packages/2f/3e/d4bde5e3ea1688b2ffc3005a6d688b20b8c8d0ef0aa24f97563c566c7d47/boolexpr-2.3-cp35-cp35m-manylinux1_x86_64.whl#md5=067b27df2b4a69c6d42371964ed80b46)

**Comment by cjdrake** [comment]
Release 2.4 should have the fix.
