### ISSUE TITLE
AttributeError from Context __del__

### ISSUE THREAD

**Issue by cjdrake** [cjdrake/boolexpr#22]
This exception was observed by shader@ while testing the `precedence` repo:

```
Exception ignored in: <bound method Context.__del__ of <boolexpr.wrap.Context object at 0x7ffff2dc1400>>                                                                                             
Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/boolexpr/wrap.py", line 295, in __del__
AttributeError: 'NoneType' object has no attribute 'boolexpr_Context_del'
Exception ignored in: Exception ignored in: Exception ignored in: Exception ignored in: <bound method Context.__del__ of <boolexpr.wrap.Context object at 0x7ffff1a68d30>>                           
Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/boolexpr/wrap.py", line 295, in __del__
AttributeError: 'NoneType' object has no attribute 'boolexpr_Context_del'
```

The `boolexpr_Context_del` method is only called on object destruction, so we need to investigate the robustness of the C++/Python layer for handling Context objects.

**Comment by cjdrake** [comment]
Okay, I think I misunderstood this error when I first looked at it.

The object that is `None` is the `lib` object, returned from `ffi.dlopen(libpath)`.

This is an odd failure. Is something over-writing `boolexpr.lib` ? Is it some strange interaction between pytest and Python's garbage collector?
