### ISSUE TITLE
windows 10 python 3.6.5 import error

### ISSUE THREAD

**Issue by 7763sea** [cjdrake/boolexpr#31]
import boolexpr
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python36\lib\site-packages\boolexpr\__init__.py", line 281, in <module>
    lib = ffi.dlopen(libpath)
  File "C:\Program Files\Python36\lib\site-packages\cffi\api.py", line 141, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
  File "C:\Program Files\Python36\lib\site-packages\cffi\api.py", line 802, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
  File "C:\Program Files\Python36\lib\site-packages\cffi\api.py", line 798, in _load_backend_lib
    return backend.load_library(path, flags)
OSError: cannot load library 'C:\Program Files\Python36\lib\site-packages\boolexpr\_boolexpr.cp36-win_amd64.pyd': error 0x7e

**Comment by cjdrake** [comment]
I don't have a Windows development machine at the moment, so can't help out.

**Comment by 7763sea** [comment]
ok，thanks。

**Comment by 7763sea** [comment]
The project is great, but there are too few people to pay attention to.
Thank you for your contribution
 How to  dump large variable,i use numpy.savez and pickle.dump,was failed.


Traceback (most recent call last):
  File "***.py", line 19, in <module>
    ******(t,20)
  File "/home/***/Desktop/sat/cnf/**.py", line 80, in ****
    pickle.dump(tmp, f, 0)
  File "/usr/lib/python3.5/copyreg.py", line 65, in _reduce_ex
    raise TypeError("can't pickle %s objects" % base.__name__)
TypeError: can't pickle CData objects

**Comment by cjdrake** [comment]
I remember quite a while ago someone else asked me about pickling. The C++/Python interface makes it a bit complicated to pull off; you might want to look into other ways of doing serialization. For example, the `from_ast` and `to_ast` methods convert expressions to/from a more generic data structure.

**Comment by 7763sea** [comment]
to_ast is slow ,to_dot success,but less than optmal
