### ISSUE TITLE
when i use boolexpr ,error occured

### ISSUE THREAD

**Issue by 7763sea** [cjdrake/boolexpr#32]
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/boolexpr/wrap.py", line 367, in __del__
AttributeError: 'NoneType' object has no attribute 'boolexpr_BoolExpr_del'
Exception ignored in: <bound method Context.__del__ of <boolexpr.wrap.Context object at 0x7feb2410a4e0>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/boolexpr/wrap.py", line 295, in __del__
AttributeError: 'NoneType' object has no attribute 'boolexpr_Context_del'
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/boolexpr/wrap.py", line 367, in __del__
AttributeError: 'NoneType' object has no attribute 'boolexpr_BoolExpr_del'

**Comment by 7763sea** [comment]
I found the reason 
file1.py ,file2.py

in file.py 
import boolexpr as bx 
btx = bx.Context()

in file2.py
from file1 impor *
import boolexpr as bx 
btx = bx.Context()
